### ISSUE TITLE
aldryn-django migrate does not return the correct exit code

### ISSUE THREAD

**Issue by stefanfoulis** [divio/aldryn-django#13]
The code (https://github.com/aldryn/aldryn-django/blob/e423a97797225c26d3f484bb0dd4a69332d786e8/aldryn_django/cli.py#L58) suggests it should work. But in practice it does not:

calling `python manage.py syncdb --noinput` directly works as expected. exit code is `1`.

```
root@77be7af91397:/app# python manage.py syncdb --noinput
Starting new HTTPS connection (1): control.local.aldryn.net
/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Registering auto field: djangocms_link.fields.PageSearchField
Registering new field: djangocms_link.fields.PageSearchField; With actual id: ba6ec61ac643ff9dbf891ddb693187a65704858a
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, ALLOWED_INCLUDE_ROOTS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_LOADERS.
/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Operations to perform:
  Synchronize unmigrated apps: aldryn_devsync, mptt, aldryn_boilerplates, aldryn_django_cms, aldryn_django, staticfiles, parler, messages, djangocms_admin_style, sitemaps, compressor, aldryn_addons, polymorphic, django_select2, sekizai, treebeard
  Apply all migrations: cmsplugin_filer_file, cmsplugin_filer_image, menus, reversion, aldryn_sso, filer, admin, djangocms_link, sessions, robots, auth, sites, captcha, contenttypes, djangocms_googlemap, djangocms_text_ckeditor, cms, easy_thumbnails, djangocms_snippet
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/virtualenv/lib/python2.7/site-packages/aldryn_django/startup.py", line 11, in manage
    utility.execute()
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists

root@77be7af91397:/app# echo $?
1
```

calling `aldryn-django migrate` returns the wrong exit code of `0`

```
root@77be7af91397:/app# aldryn-django migrate
aldryn-django: running migration commands
    ----> CACHE_URL="locmem://" python manage.py createcachetable django_dbcache; exit 0
Starting new HTTPS connection (1): control.local.aldryn.net
/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Registering auto field: djangocms_link.fields.PageSearchField
Registering new field: djangocms_link.fields.PageSearchField; With actual id: ba6ec61ac643ff9dbf891ddb693187a65704858a
Cache table 'django_dbcache' already exists.





    ----> python manage.py syncdb --noinput
Starting new HTTPS connection (1): control.local.aldryn.net
/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/virtualenv/lib/python2.7/site-packages/aldryn_boilerplates/template_loaders.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Registering auto field: djangocms_link.fields.PageSearchField
Registering new field: djangocms_link.fields.PageSearchField; With actual id: ba6ec61ac643ff9dbf891ddb693187a65704858a
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, ALLOWED_INCLUDE_ROOTS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_LOADERS.
/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Operations to perform:
  Synchronize unmigrated apps: aldryn_devsync, mptt, aldryn_boilerplates, aldryn_django_cms, aldryn_django, staticfiles, parler, messages, djangocms_admin_style, sitemaps, compressor, aldryn_addons, polymorphic, django_select2, sekizai, treebeard
  Apply all migrations: cmsplugin_filer_file, cmsplugin_filer_image, menus, reversion, aldryn_sso, filer, admin, djangocms_link, sessions, robots, auth, sites, captcha, contenttypes, djangocms_googlemap, djangocms_text_ckeditor, cms, easy_thumbnails, djangocms_snippet
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/virtualenv/lib/python2.7/site-packages/aldryn_django/startup.py", line 11, in manage
    utility.execute()
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/virtualenv/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/virtualenv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/virtualenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists

root@77be7af91397:/app# echo $?
0
```

Processing does seem to stop after the first failed command though (`python manage.py migrate...` is never called).
Probably `click` is swallowing the exit code.

**Comment by stefanfoulis** [comment]
http://click.pocoo.org/5/exceptions/#where-are-errors-handled
