### ISSUE TITLE
Opbeat archived

### ISSUE THREAD

**Issue by arnodeceuninck** [divio/aldryn-django#225]
`pip install aldryn-django` doesn't work anymore on the newest python versions, since opbeat doesn't support them. Is there any alternative for this? 

Current error I'm getting (because of the reserved "async" keyword):
```
Collecting opbeat
  Using cached opbeat-3.6.1.tar.gz (81 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/arno/Documents/website/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xy3kxj6b/opbeat/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xy3kxj6b/opbeat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xy3kxj6b/opbeat/pip-egg-info
         cwd: /tmp/pip-install-xy3kxj6b/opbeat/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xy3kxj6b/opbeat/setup.py", line 28, in <module>
        from opbeat.version import VERSION
      File "/tmp/pip-install-xy3kxj6b/opbeat/opbeat/__init__.py", line 20, in <module>
        from opbeat.base import *
      File "/tmp/pip-install-xy3kxj6b/opbeat/opbeat/base.py", line 122
        async=None, async_mode=None, traces_send_freq_secs=None,
        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by FinalAngel** [comment]
@arnodeceuninck aldryn-django should not be installed through pip as it is a dependency that runs on Divio Cloud only. It should be installed through the addons interface. Alternatively, you may need to grab the specific version from your ``requirements.ini`` file.
